### ISSUE TITLE
Spanish for Argentina

### ISSUE THREAD

**Issue by nilhuh** [IndexBraille/liblouis#3]
Printing Errors:

The errors that we will detail below, already come from the time of Everest V4 printers, Index Braille technicians sent us an IBE file to add to the printer and correct errors. With Everest V5 we do not want to do the same without the approval of the technicians. Perhaps there is another way to correct such errors.

It is important to correct these printing errors because we use the same Braille System for both Hispanics and Spaniards. I do not know which table to select, but I tried with both tables present in the configurations of, Grade 1 Version 1 - Grade 1 Version 2, and it is not the braille system that we use.

To clarify that with the table Grade 1 Version 2 is more like our Braille system but with the following errors:

1. The sign Arroba, @, is being printed with points 56-16, and most Spanish and Hispanic users use point 5 to write that sign.

2. The sign closes admiration (!), is being printed with 256 points, and Hispanic and Spanish users write that sign with points 235.

3. The fractions are being printed with the number sign on the other side, 1456, and we write the number sign with the points 3456. For example, ½ we write with points 3456-2-12.

**Comment by simait** [comment]
Issue 2 is fixed in the Spanish table as well, liblouis/liblouis#373, so need to fix it here...

**Comment by simait** [comment]
And the rest of the fixes are merged in liblouis/liblouis#398.
